apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: LoadBalancer
